steps:
  # Build the docker images:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Creating Docker'
    args: ['build','-t','us-central1-docker.pkg.dev/sublime-state-413617/ci-cd-batch-bank-churn/bank-batch-pred:$COMMIT_SHA','.']

# Push the docker image to artifact

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pushing Docker to AR'
    args: ['push','us-central1-docker.pkg.dev/sublime-state-413617/ci-cd-batch-bank-churn/bank-batch-pred:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    id:  'Upload Model'
    args: ['ai','models','upload',
           '--container-image-uri=us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.1-2:latest',
           '--description=ci-cd-bank-churn',
           '--display-name=ci-cd-bank-churn-vertex-ai',
           '--artifact-uri=gs://model-collections-v1/',
           '--project=sublime-state-413617',
           '--region=us-central1']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Fetch Model Id'
    entrypoint: 'bash'
    args: ['-c', 'gcloud ai models list --region=us-central1 --project=sublime-state-413617 --format="get(MODEL_ID)" --sort-by="createTime" --limit=1 > /workspace/model_id.txt']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Endpoint'
    entrypoint: 'bash'
    args: ['-c', 'gcloud beta ai endpoints create --display-name=ci-cd-bank-churn-vertex-ai-endpoint --format="get(name)" --region=us-central1 --project=sublime-state-413617 > /workspace/endpoint_id.txt']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Model Endpoint'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta ai endpoints deploy-model $(cat /workspace/endpoint_id.txt) --region=us-central1 --model=$(cat /workspace/model_id.txt) --display-name=ci-cd-bank-churn-vertex-ai-endpoint --traffic-split=0=100 --machine-type=n1-standard-4

options:
  logging: CLOUD_LOGGING_ONLY
